### ISSUE TITLE
[Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext] does not contain a method named 'AcquireToken'

### ISSUE THREAD

**Issue by HoCGeek** [jasonfritts/AADReportingAPI#1]
I copied the Update MSGraphSignInsDownload.ps1 script directly into my ISE, populated the variable for $tenantID, and got this error on first run.  Am I missing something?

**Comment by jasonfritts** [comment]
@HoCGeek that looks to be like an issue with the Azure module not be loaded or perhaps there is an issue with a later version which hasnt been tested.  Can you confirm you have installed the Azure module per per-requisites in the readme doc and also verify what version you have loaded  you can use get-module -ListAvailable Azure

**Comment by HoCGeek** [comment]
Sorry – the issue may have been on my end.  I had installed and loaded the module (v5.3.1) when I first tried your script so I was using a recent version, but was getting the error I noted, but I tried again this morning (my PC rebooted over the weekend) it appears to be working fine.  Sorry if I’ve caused any unnecessary confusion, and thanks for following up/getting back to me.

Dan

**Comment by jasonfritts** [comment]
Great, glad to hear it is working!
