### ISSUE TITLE
Filter for legacy authentication

### ISSUE THREAD

**Issue by aakash-shah** [jasonfritts/AADReportingAPI#2]
I have a suggestion: can you offer the ability to filter the results to only pull/show legacy authentication connections only?

Thanks!

**Comment by jasonfritts** [comment]
@aakash-shah the new [MSGraph SDK Module](https://docs.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-beta) example at https://github.com/jasonfritts/AADReportingAPI/blob/master/MSGraphSDK_ExportLogs.ps1 should do just that.
